export const HERO_ORDER = ['junior', 'trick', 'dunk', 'king', 'jones'];

export const HEROES = {
  junior: {
    id: 'junior',
    name: 'Super Junior',
    blurb: 'Le chef courageux.',
    line: "J'irai te chercher, Maman !",
    speed: 6,
    attack: 10,
    dashAttack: 18,
    barrierRadius: 1.15,
    barrierMove: 0.65,
    dashDistance: 4.5,
    dashDuration: 0.28,
    radius: 0.42,
    attackRange: 1.9,
    attackArc: 0.95,
    weapon: 'sword',
    tunic: '#3d5a80',
    accent: '#c0392b',
    hair: '#5a3825',
    timings: { windup: 80, active: 220, recovery: 400 },
    perfect: { kind: 'attackBuff', mul: 1.5, duration: 3 },
  },
  trick: {
    id: 'trick',
    name: 'Super Trick',
    blurb: 'Le stratège ingénieux.',
    line: 'Point faible trouvé !',
    speed: 6,
    attack: 8,
    dashAttack: 14,
    barrierRadius: 1.2,
    barrierMove: 0.7,
    dashDistance: 4.5,
    dashDuration: 0.26,
    radius: 0.42,
    attackRange: 2.05,
    attackArc: 0.75,
    weapon: 'orb',
    tunic: '#2e86ab',
    accent: '#f4d35e',
    hair: '#3b2f2f',
    timings: { windup: 80, active: 220, recovery: 400 },
    perfect: { kind: 'defenseDown', mul: 1.5, banner: 'Point faible trouvé !' },
  },
  dunk: {
    id: 'dunk',
    name: 'Super Dunk',
    blurb: 'Le plus fort.',
    line: 'Un coup, et ça tombe !',
    speed: 4.8,
    attack: 16,
    dashAttack: 28,
    barrierRadius: 1.6,
    barrierMove: 0.6,
    dashDistance: 3.2,
    dashDuration: 0.34,
    radius: 0.55,
    attackRange: 2.45,
    attackArc: 1.4,
    weapon: 'hammer',
    tunic: '#e07a3d',
    accent: '#f4d03f',
    hair: '#4a2c14',
    timings: { windup: 120, active: 320, recovery: 560 },
    perfect: { kind: 'stun', duration: 1.2 },
  },
  king: {
    id: 'king',
    name: 'Super King',
    blurb: 'Le calme et majestueux.',
    line: 'Ensemble, nous sommes plus forts.',
    speed: 6,
    attack: 8,
    dashAttack: 14,
    barrierRadius: 2.0,
    barrierMove: 0.7,
    dashDistance: 4.2,
    dashDuration: 0.3,
    radius: 0.45,
    attackRange: 2.15,
    attackArc: 0.85,
    weapon: 'scepter',
    tunic: '#1e7a46',
    accent: '#d4af37',
    hair: '#c9a36a',
    timings: { windup: 80, active: 220, recovery: 400 },
    perfect: { kind: 'heal', hearts: 1 },
  },
  jones: {
    id: 'jones',
    name: 'Super Jones',
    blurb: 'Le rapide et agile.',
    line: 'Trop tard. Je suis déjà derrière.',
    speed: 8.1,
    attack: 10,
    dashAttack: 18,
    barrierRadius: 0.9,
    barrierMove: 0.75,
    dashDistance: 7.2,
    dashDuration: 0.22,
    radius: 0.36,
    attackRange: 1.65,
    attackArc: 0.7,
    weapon: 'dagger',
    tunic: '#6c3483',
    accent: '#1a1224',
    hair: '#1b1210',
    timings: { windup: 50, active: 140, recovery: 260 },
    perfect: { kind: 'none' },
    teleportDashAttack: true,
  },
};

export const PLAYER_MAX_HP = 5;

export const EXIT_HINT = {
  north: 'La porte est devant. Appuie sur L.',
  east: 'La porte est à droite. Appuie sur L.',
  west: 'La porte est à gauche. Appuie sur L.',
  up: "En haut de l'escalier, appuie sur L.",
  down: "En bas de l'escalier, appuie sur L.",
};

export const ROOMS = [
  { title: 'Le hall', enemy: 'goblin', exit: 'north', goal: 'Un gobelin. La porte est devant.' },
  { title: 'Le couloir', enemy: 'skeleton', exit: 'east', goal: 'Un squelette. La porte est à droite.' },
  { title: "L'escalier", enemy: 'golem', exit: 'up', goal: "Un golem. Monte l'escalier." },
  { title: 'La galerie', enemy: 'orc', exit: 'west', goal: 'Un orc. La porte est à gauche.' },
  { title: 'Le balcon', enemy: 'witch', exit: 'north', goal: 'Une sorcière. La porte est devant.' },
  { title: 'La descente', enemy: 'sorceress', exit: 'down', goal: "Une magicienne. Descends l'escalier." },
  { title: 'La salle est', enemy: 'demon', exit: 'east', goal: 'Un démon. La porte est à droite.' },
  { title: 'La cave', enemy: 'troll', exit: 'west', goal: 'Un troll. La porte est à gauche.' },
  { title: 'La montée', enemy: 'zombie-barefoot', exit: 'up', goal: 'Un zombie. Monte vers la porte.' },
  { title: 'Le poste', enemy: 'zombie-cop', exit: 'north', goal: 'Un zombie policier. La porte est devant.' },
  { title: "L'infirmerie", enemy: 'zombie-doctor', exit: 'east', goal: 'Un zombie médecin. La porte est à droite.' },
  { title: 'Le sol', enemy: 'zombie-doctor-crawl', exit: 'down', goal: 'Un médecin rampant. Descends.' },
  { title: 'La garde', enemy: 'zombie-guard', exit: 'west', goal: 'Un zombie gardien. La porte est à gauche.' },
  { title: 'Le salon', enemy: 'goth-girl', exit: 'up', goal: 'Une fille gothique. Monte vers la porte.' },
  { title: 'La salle du roi', boss: true, goal: 'Patricia est ici. Bats Pierre Vert.' },
];

function foe(model, name, extra = {}) {
  return {
    kind: model,
    name,
    model,
    behavior: 'slime',
    hp: 16,
    speed: 1.45,
    attack: 1,
    radius: 0.5,
    telegraph: 0.8,
    strike: 0.3,
    recover: 0.88,
    blockable: true,
    ...extra,
  };
}

export const ENEMIES = {
  goblin: foe('goblin', 'Gobelin', { hp: 14, speed: 1.7, radius: 0.42 }),
  skeleton: foe('skeleton', 'Squelette', { hp: 14, speed: 1.65, radius: 0.42 }),
  golem: foe('golem', 'Golem', { hp: 10, speed: 0.8, radius: 0.7, telegraph: 1.2 }),
  orc: foe('orc', 'Orc', { hp: 16, radius: 0.5 }),
  witch: foe('witch', 'Sorcière', { hp: 14, radius: 0.45 }),
  sorceress: foe('sorceress', 'Magicienne', { hp: 14, speed: 1.55, radius: 0.45 }),
  demon: foe('demon', 'Démon', { behavior: 'knight', hp: 20, speed: 1.35, radius: 0.62 }),
  troll: foe('troll', 'Troll', { behavior: 'knight', hp: 22, speed: 1.2, radius: 0.72 }),
  'zombie-barefoot': foe('zombie-barefoot', 'Zombie', { hp: 16, speed: 1.25, radius: 0.48 }),
  'zombie-cop': foe('zombie-cop', 'Zombie policier', { hp: 16, speed: 1.35, radius: 0.48 }),
  'zombie-doctor': foe('zombie-doctor', 'Zombie médecin', { hp: 16, speed: 1.3, radius: 0.48 }),
  'zombie-doctor-crawl': foe('zombie-doctor-crawl', 'Médecin rampant', { hp: 14, speed: 0.95, radius: 0.55 }),
  'zombie-guard': foe('zombie-guard', 'Zombie gardien', { behavior: 'knight', hp: 18, speed: 1.25, radius: 0.52 }),
  'goth-girl': foe('goth-girl', 'Fille gothique', { hp: 14, speed: 1.6, radius: 0.42 }),
  pierre: {
    kind: 'pierre',
    name: 'Pierre Vert',
    model: 'orc-ogre',
    behavior: 'pierre',
    hp: 28,
    speed: 1.15,
    attack: 1,
    radius: 0.9,
    telegraph: 1.2,
    recover: 1.25,
  },
};

export const STORY_PAGES = [
  {
    title: 'Le départ',
    body: [
      'Patricia, la maman aimante, est prisonnière de Pierre Vert.',
      'Cinq amis partent vers le château.',
      "« J'irai te chercher, Maman ! »",
    ],
  },
  {
    title: 'Les monstres',
    body: [
      'Chaque salle cache un seul monstre. Démons, orcs, zombies.',
      'Le chemin tourne à gauche, à droite, et monte des escaliers.',
      'Bats le monstre, puis ouvre la porte avec L.',
    ],
  },
  {
    title: 'Retrouver maman',
    body: [
      'Patricia attend derrière les barreaux.',
      'Elle voit la lumière des torches, et elle espère.',
      '« Mes enfants... Je vous attends. Je crois en vous. »',
    ],
  },
  {
    title: 'Pierre Vert',
    body: [
      'Pierre Vert est dans la dernière salle, avec Patricia.',
      'Sa défense est immense. Une barrière parfaite la brise.',
      'Ensuite on fonce et on attaque.',
    ],
  },
  {
    title: 'Ensemble',
    body: [
      'Patricia est libre.',
      'On rentre ensemble, sous les étoiles.',
      'Le lien de la famille ne se brise pas.',
    ],
  },
];

export const COPY = {
  title: 'Les 5 héros en quête de Patricia',
  selectSubtitle: 'Cinq amis. Un seul but. Retrouver maman Patricia.',
  choose: 'Choisir',
  readStory: "Lire l'histoire",
  next: 'Suite',
  back: 'Retour',
  play: 'Jouer',
  replay: 'Rejouer',
  continue: 'Continuer',
  life: 'Vie',
  move: 'Déplacement',
  barrier: 'Barrière',
  attack: 'Attaque',
  dash: 'Dash',
  courtyard: 'La cour du château',
  cageSeen: 'Patricia est là. Elle est enfermée.',
  gateOpen: "La porte du trône s'ouvre.",
  throne: 'Affronter Pierre Vert',
  rescue: 'Patricia est libre. Rentrons ensemble.',
  perfect: 'Barrière parfaite !',
  weak: 'Point faible trouvé !',
  broken: 'Défense brisée !',
  dodgeT: 'Esquive avec T !',
  pressK: 'Appuie sur K !',
  pressKBarrier: 'Appuie sur K ! Barrière !',
  pressKPerfect: 'Appuie sur K ! Barrière parfaite !',
  punch: 'Coup de poing',
  wave: 'Vague de slime',
  rain: 'Pluie de slime',
  charge: 'Charge du roi',
  keyGot: 'Tu as la clé !',
  doorHint: 'Va à la porte. Appuie sur L.',
  pressL: 'Appuie sur L',
  doorLocked: 'La porte est fermée. Bats le monstre.',
  doorOpens: 'La porte s\'ouvre.',
  loading: 'Le monstre approche...',
  hasKey: 'Clé',
  kingGoal: 'Patricia est ici. Appuie sur K quand le roi attaque.',
  fallen: "Tu es tombé. Tes amis t'attendent. Recommence.",
  pierre: 'Pierre Vert',
};
